import { v } from "convex/values";
import { action, internalMutation, internalQuery } from "./_generated/server";
import { api, internal } from "./_generated/api";
import Anthropic from "@anthropic-ai/sdk";

// Initialize Anthropic client
const anthropic = new Anthropic({
  apiKey: process.env.ANTHROPIC_API_KEY!,
});

/**
 * Generate a comprehensive SEO-optimized blog post about tractors/machinery
 * using Claude Haiku 4.5
 */
export const generateBlogPost = action({
  args: {
    topic: v.string(), // e.g., "1950 Ford 8N Tractor"
    keywords: v.optional(v.string()), // Optional additional keywords
    tone: v.optional(v.union(
      v.literal("professional"),
      v.literal("casual"),
      v.literal("enthusiast"),
      v.literal("technical")
    )),
  },
  handler: async (ctx, { topic, keywords = "", tone = "professional" }) => {
    // Verify user is authenticated
    const userId = await ctx.runQuery(internal.aiBlogGeneration.getCurrentUserId);
    if (!userId) {
      throw new Error("Must be authenticated to generate blog posts");
    }

    // Create the prompt for Claude
    const prompt = `You are an expert content writer specializing in vintage tractors, agricultural machinery, and equipment restoration. 

Write a comprehensive, SEO-optimized blog post about: "${topic}"

Requirements:
- Length: 1200-1800 words
- Tone: ${tone}
- Include specific technical details, history, and restoration insights
- Use H2 and H3 headings to structure the content
- Include a compelling introduction and conclusion
- Natural keyword integration: ${keywords || topic}
- Write in HTML format with proper heading tags, paragraphs, and lists
- Make it engaging for both restoration enthusiasts and general audiences
- Include maintenance tips, historical context, and collector value insights
- Use specific model numbers, years, and technical specifications when relevant

Additional keywords to naturally incorporate: ${keywords}

Format your response as valid HTML that can be directly inserted into a blog post. Use <h2>, <h3>, <p>, <ul>, <li>, <strong>, <em> tags as needed. Do NOT include <html>, <head>, or <body> tags - just the article content.

Start with a compelling opening paragraph that hooks the reader, then provide detailed sections with clear headings.`;

    try {
      // Call Claude Haiku 4.5 API
      const message = await anthropic.messages.create({
        model: "claude-3-5-haiku-20241022", // Claude Haiku 4.5
        max_tokens: 4096,
        temperature: 0.7,
        messages: [
          {
            role: "user",
            content: prompt,
          },
        ],
      });

      // Extract the generated content
      const content = message.content[0].type === "text" 
        ? message.content[0].text 
        : "";

      if (!content) {
        throw new Error("No content generated from AI");
      }

      // Generate SEO metadata
      const metaTitle = await generateMetaTitle(topic);
      const metaDescription = await generateMetaDescription(content, topic);
      const excerpt = await generateExcerpt(content);
      const tags = await generateTags(topic, keywords);
      const slug = generateSlug(topic);

      // Create the draft blog post
      const blogPostId = await ctx.runMutation(internal.aiBlogGeneration.createDraftPost, {
        title: topic,
        slug,
        content,
        excerpt,
        metaTitle,
        metaDescription,
        tags,
        aiPrompt: prompt,
        userId,
      });

      return {
        success: true,
        blogPostId,
        preview: {
          title: topic,
          slug,
          excerpt,
          metaTitle,
          metaDescription,
          tags,
          wordCount: content.split(/\s+/).length,
        },
      };
    } catch (error: any) {
      console.error("AI generation error:", error);
      throw new Error(`Failed to generate blog post: ${error.message}`);
    }
  },
});

/**
 * Auto-generate 1-2 draft blog posts for admin review
 * This can be called manually or scheduled via cron
 */
export const autoGenerateDrafts = action({
  args: {
    count: v.optional(v.number()), // Number of drafts to generate (1-2)
  },
  handler: async (ctx, { count = 2 }) => {
    // Verify user is authenticated (for manual trigger) or skip for cron
    try {
      const userId = await ctx.runQuery(internal.aiBlogGeneration.getCurrentUserId);
      if (!userId) {
        // If no user (cron job), use system generation
        console.log("Auto-generating drafts via cron job");
      }
    } catch (e) {
      console.log("Running as scheduled job");
    }

    // List of popular tractor/machinery topics for auto-generation
    const topics = [
      "John Deere Model A Tractor Restoration Guide",
      "Farmall Cub: The Perfect Small Farm Tractor",
      "Allis-Chalmers WD-45: History and Restoration",
      "Ford 8N Tractor: America's Favorite Utility Tractor",
      "Case IH Magnum Series: Power and Performance",
      "International Harvester Cub Cadet: Collector's Guide",
      "Massey Ferguson 35: The World's Best-Selling Tractor",
      "Oliver 77 Row Crop: A Green Machine Classic",
      "Minneapolis-Moline U: The Unique Prairie Tractor",
      "Farmall M: Heavy-Duty Farming Power",
      "John Deere 4020: The Legendary Workhorse",
      "Ford 9N: The Tractor That Changed Farming",
      "Allis-Chalmers B: The Small Tractor with Big Impact",
      "Case VAC: The Streamlined Farm Tractor",
      "International Harvester 560: The Troublesome Legend",
    ];

    // Randomly select topics
    const selectedTopics = [];
    const usedIndices = new Set<number>();
    
    for (let i = 0; i < Math.min(count, 2); i++) {
      let randomIndex;
      do {
        randomIndex = Math.floor(Math.random() * topics.length);
      } while (usedIndices.has(randomIndex));
      
      usedIndices.add(randomIndex);
      selectedTopics.push(topics[randomIndex]);
    }

    // Generate drafts
    const results = [];
    for (const topic of selectedTopics) {
      try {
        const result = await ctx.runAction(api.aiBlogGeneration.generateBlogPost, {
          topic,
          tone: "enthusiast",
        });
        results.push(result);
      } catch (error: any) {
        console.error(`Failed to generate draft for "${topic}":`, error);
        results.push({ success: false, topic, error: error.message });
      }
    }

    return {
      success: true,
      generated: results.filter(r => r.success).length,
      failed: results.filter(r => !r.success).length,
      results,
    };
  },
});

/**
 * Internal query to get current user ID
 */
export const getCurrentUserId = internalQuery({
  args: {},
  handler: async (ctx) => {
    const userId = await ctx.auth.getUserIdentity();
    return userId?.subject;
  },
});

/**
 * Internal mutation to create a draft blog post
 */
export const createDraftPost = internalMutation({
  args: {
    title: v.string(),
    slug: v.string(),
    content: v.string(),
    excerpt: v.optional(v.string()),
    metaTitle: v.optional(v.string()),
    metaDescription: v.optional(v.string()),
    tags: v.optional(v.string()),
    aiPrompt: v.string(),
    userId: v.string(),
  },
  handler: async (ctx, args) => {
    const now = Date.now();
    
    // Ensure slug is unique
    let slug = args.slug;
    let counter = 1;
    while (true) {
      const existing = await ctx.db
        .query("blogPosts")
        .withIndex("by_slug", (q) => q.eq("slug", slug))
        .first();
      
      if (!existing) break;
      slug = `${args.slug}-${counter}`;
      counter++;
    }

    return await ctx.db.insert("blogPosts", {
      title: args.title,
      slug,
      content: args.content,
      excerpt: args.excerpt,
      metaTitle: args.metaTitle,
      metaDescription: args.metaDescription,
      tags: args.tags,
      published: false,
      status: "draft",
      aiGenerated: true,
      aiPrompt: args.aiPrompt,
      userId: args.userId as any,
      createdAt: now,
      updatedAt: now,
    });
  },
});

// Helper functions for SEO metadata generation

function generateSlug(title: string): string {
  return title
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "")
    .substring(0, 60);
}

async function generateMetaTitle(topic: string): Promise<string> {
  // Create SEO-optimized title (max 60 chars)
  const title = topic.length <= 55 
    ? `${topic} Guide` 
    : topic.substring(0, 60);
  return title;
}

async function generateMetaDescription(content: string, topic: string): Promise<string> {
  // Extract first paragraph or create description
  const textContent = content.replace(/<[^>]*>/g, " ").replace(/\s+/g, " ").trim();
  const description = textContent.substring(0, 155) + "...";
  return description;
}

async function generateExcerpt(content: string): Promise<string> {
  // Extract first 2-3 sentences
  const textContent = content.replace(/<[^>]*>/g, " ").replace(/\s+/g, " ").trim();
  const sentences = textContent.match(/[^.!?]+[.!?]+/g) || [];
  const excerpt = sentences.slice(0, 2).join(" ");
  return excerpt.substring(0, 300);
}

async function generateTags(topic: string, keywords: string): Promise<string> {
  // Extract relevant tags from topic and keywords
  const words = [...topic.split(" "), ...keywords.split(" ")];
  const tags = new Set<string>();
  
  // Common tractor-related tags
  const relevantTerms = ["tractor", "restoration", "vintage", "antique", "farming", 
    "agriculture", "machinery", "equipment", "diesel", "collector"];
  
  words.forEach(word => {
    const cleanWord = word.toLowerCase().replace(/[^a-z0-9]/g, "");
    if (cleanWord.length > 3 && !["the", "and", "for", "with"].includes(cleanWord)) {
      tags.add(cleanWord);
    }
  });
  
  // Add relevant general tags
  relevantTerms.forEach(term => {
    if (topic.toLowerCase().includes(term) || keywords.toLowerCase().includes(term)) {
      tags.add(term);
    }
  });
  
  return Array.from(tags).slice(0, 8).join(", ");
}
