import { cronJobs } from "convex/server";
import { internal } from "./_generated/api";

const crons = cronJobs();

// Publish scheduled posts - runs every hour
crons.interval(
  "publish scheduled posts",
  { hours: 1 },
  internal.scheduledPosts.publishScheduledPosts
);

// Auto-generate draft posts - runs daily at 3 AM
crons.daily(
  "auto-generate draft posts",
  { hourUTC: 3, minuteUTC: 0 },
  internal.scheduledPosts.autoGenerateDailyDrafts
);

export default crons;
