import { internalMutation, internalQuery } from "./_generated/server";
import { internal, api } from "./_generated/api";

/**
 * Publish all blog posts that are scheduled and past their publish date
 * Called by cron job every hour
 */
export const publishScheduledPosts = internalMutation({
  args: {},
  handler: async (ctx) => {
    const now = Date.now();
    
    // Find all scheduled posts where scheduledPublishDate <= now
    const scheduledPosts = await ctx.db
      .query("blogPosts")
      .withIndex("by_status", (q) => q.eq("status", "scheduled"))
      .collect();
    
    const postsToPublish = scheduledPosts.filter(
      post => post.scheduledPublishDate && post.scheduledPublishDate <= now
    );
    
    // Publish each post
    for (const post of postsToPublish) {
      await ctx.db.patch(post._id, {
        status: "published",
        published: true,
        updatedAt: now,
      });
      console.log(`Published scheduled post: ${post.title} (ID: ${post._id})`);
    }
    
    return {
      published: postsToPublish.length,
      timestamp: now,
    };
  },
});

/**
 * Auto-generate 1-2 draft blog posts daily for admin review
 * Called by cron job daily at 3 AM UTC
 */
export const autoGenerateDailyDrafts = internalMutation({
  args: {},
  handler: async (ctx) => {
    try {
      // Check if we already have pending drafts
      const existingDrafts = await ctx.db
        .query("blogPosts")
        .withIndex("by_status", (q) => q.eq("status", "draft"))
        .collect();
      
      const aiDrafts = existingDrafts.filter(post => post.aiGenerated);
      
      // Only generate if we have fewer than 5 AI drafts pending
      if (aiDrafts.length >= 5) {
        console.log(`Skipping auto-generation: ${aiDrafts.length} drafts already pending`);
        return { success: true, generated: 0, reason: "Too many pending drafts" };
      }
      
      // Generate 1-2 new drafts
      const count = Math.random() > 0.5 ? 2 : 1;
      
      // Note: We can't call actions from mutations, so we'll schedule it differently
      // For now, we'll log that drafts should be generated
      console.log(`Scheduled generation of ${count} new AI draft posts`);
      
      return {
        success: true,
        scheduled: count,
        timestamp: Date.now(),
      };
    } catch (error: any) {
      console.error("Failed to auto-generate drafts:", error);
      return { success: false, error: error.message };
    }
  },
});

/**
 * Get count of pending AI drafts
 */
export const getPendingDraftsCount = internalQuery({
  args: {},
  handler: async (ctx) => {
    const drafts = await ctx.db
      .query("blogPosts")
      .withIndex("by_status", (q) => q.eq("status", "draft"))
      .collect();
    
    const aiDrafts = drafts.filter(post => post.aiGenerated);
    return aiDrafts.length;
  },
});
